# Generated by Django 4.0.5 on 2022-06-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_infoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('supervisor', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
